FROM python:3.10.14-alpine3.19

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Update package index and install necessary system dependencies
RUN apk update \
    && apk add gcc musl-dev

# Copy requirements.txt and install dependencies
COPY ./app/requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY ./app/main.py .

# Specify the command to run the application
CMD ["uvicorn", "main:app","--host", "0.0.0.0","--port", "8000"]
